language: go
os:
  - linux
  - osx
go:
  - "1.10.1"
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install bash; fi
  - bash --version ; type bash
  - go get github.com/docopt/docopt-go
  # get our official repos too
  - go get github.com/docopt/docopts
branches:
  only:
    - docopts-go
    - master
    - rdonkin-feat-bash-3.2-support
notifications:
  email:
    on_success: never
script:
  - make test
    #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash -x ./travis/reverse_ssh_tunnel.sh ; fi
